# ~/.config/starship.toml

add_newline = true

[package]
disabled = true

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[directory]
truncation_length = 5
style = "bold cyan"

[git_branch]
symbol = "[ ](bold magenta)"

[cmd_duration]
disabled = true
