# ~/.config/starship.toml

add_newline = true 

format = """
$directory\
$git_branch\
$git_status\
$line_break\
$character"""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[󰬅](bold red)"

[directory]
truncation_length = 5
style = "bold cyan"

[git_branch]
symbol = "[ ](bold purple)"

[git_status]
ahead = ""
behind = ""
staged = ""
renamed = "󰑕"

[cmd_duration]
disabled = true

[package]
disabled = true

